### ISSUE TITLE
Wire-up Ontology name, class name to display in Header in Graph Manager 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#3735] opened 2018-07-23 21:26 UTC
When clicked. each node in a branch or model tree displays the associated configuration form for the node.  The form has a header which displays the node name, as well as a hard-coded reference to the parent ontology and class name of the node.

Replace hard-coded strings with references to the nodes' actual ontology and class

**Comment by apeters** [comment] 2018-08-01 23:19
duplicate of #3784

**Closed by apeters** 2018-08-01 23:19 UTC
