### ISSUE TITLE
Floating UI blocks values in the coordinate editor in the map widget 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#9691] opened 2023-06-23 18:50 UTC
Clicking the "Edit Coordinates" link brings up the coordinate editor. 
The header where it says "Edit Coordinates"  and shows coordinate reference dropdown blocks the editor.  

Additionally, you can't scroll the coordinates panel when you have many coordinates to edit.

<img width="507" alt="Screenshot 2023-06-23 at 11 46 25 AM" src="https://github.com/archesproject/arches/assets/823773/9848f285-449a-4601-a8cc-ce637692b128">

**This is the panel with the issue:**
![Screenshot 2023-06-22 at 3 17 02 PM](https://github.com/archesproject/arches/assets/823773/babbf9bd-bf6e-40fd-8f89-9ae3cc1c4ba7)

**Comment by chiatt** [comment] 2023-06-23 21:50
Duplicate of #9145

**Closed by chiatt** 2023-06-23 21:50 UTC
Labels: Type: Bug
