### ISSUE TITLE
Error banner persists about missing required value after save

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches#10039] opened 2023-09-14 22:14 UTC
#### To reproduce ####
- Create a nodegroup with two required nodes.
- Create a resource: fill out only one value
- Save
- Fill out the other value
- Save

Result: error banner still persists

https://github.com/archesproject/arches/assets/38668450/540cdc63-45b7-441f-8239-fb1e62e2885b

**Comment by chiatt** [comment] 2023-09-14 22:22
This looks like it might be a duplicate of: https://github.com/archesproject/arches/issues/6957

Unfortunately that banner persists everywhere until the user dismisses it.

**Closed** 2023-09-14 22:24 UTC
