### ISSUE TITLE
Arches Collector Manager Map Extent is broken

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5789] opened 2020-01-03 19:08 UTC
Map no loner appears in UI properly, page throws an error: ![Screen Shot 2020-01-03 at 11.07.09 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/45b6f0f2-315b-4bd1-84b7-d1813c05ae19)

**Comment by chiatt** [comment] 2020-01-03 21:59
Duplicate of #5790

**Closed by chiatt** 2020-01-03 21:59 UTC
