### ISSUE TITLE
If URL is saved without label, label cannot be added in future edits

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#10593] opened 2024-02-08 09:22 UTC
Found in v6 and v7

When the URL value is saved to a card without the URL Label, then the label cannot be added in any future edits, see example:
![URL label not able to be saved](https://github.com/archesproject/arches/assets/119508494/c9dbb34b-555f-4e4d-b57e-cd0fb7f17171)

This is because the JSON object saved to the database doesn't include `"url_label": ""`

**Comment by chiatt** [comment] 2024-02-27 16:35
Thanks for submitting this @SDScandrettKint, but I'm closing it because it looks like a duplicate of #8451

**Closed by chiatt** 2024-02-27 16:35 UTC
