### ISSUE TITLE
dev/7.0.x Bug Display of the Correct Language Name in the Arches Designer Graph Interface

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches#8833] opened 2022-08-17 23:03 UTC
I'm running dev/7.0.x Arches core with the Arches HER project in order to test some internationalization features. I haven't installed Hebrew or Arabic .po files, but I'm trying to do some tests that don't depend on those.

In Arches Designer, I'm attempting to review a branch that should have an English and an Arabic name. I'm back in English user interface, and I see in the Graph interface the Arabic name for this branch. However the details for this branch displays the expected English name.

I'm using a the Brave (based on Chrome) browser in Windows 11. Screenshot is attached.

![arches-ui-bug-internationalization-name-wrong-lang](https://user-images.githubusercontent.com/1286742/185258611-3522adef-0c02-45f2-b75c-2528f5d2cc03.png)

Some additional investigation suggests that the Graph interface is displaying the most recently created instance of a name, in whatever language, for this branch. I first created an English name for the branch, then Arabic, then Hebrew, and now the Hebrew version of the branch name shows up in the Graph interface.

![arches-ui-bug-internationalization-name-wrong-lang-he](https://user-images.githubusercontent.com/1286742/185260589-8a1eb0cc-4adc-407e-aa00-c19fc0a7d1f7.png)

**Comment by robgaston** [comment] 2022-08-23 17:24
Please verify that translation of node/graph names is working as expected.

**Comment by ekansa** [comment] 2022-08-23 18:06
@robgaston I'm new to my testing set up with Arches, so apologies in advance. I can't verify the fix, but that may be a problem with me and not the fix.

I updated to the latest of on the Arches core dev/7.0.x branch:
```
10:47 $ git reset --hard origin/dev/7.0.x
HEAD is now at 6191b51d2 Merge pull request #8847 from archesproject/8830_simple_switch_rtl_ui
```

And restarted my Arches-her docker containers (with the build flag)

```
docker compose up --build
```

And I still see the Hebrew language name (which was the most recent name I created) in the Graph interface for this branch.

**Comment by robgaston** [comment] 2022-08-23 18:09
Hi @ekansa -- sorry, I should have directed my message better.  That was meant for @apeters who is going to be investigating this bug further, and based on a conversation that we had I simply wanted to note that we should investigate a bit beyond the declared scope of this issue to verify that these features are (or are not) in fact working as designed.

By the way, thanks for all your help in surfacing bugs! it's very much appreciated

**Comment by apeters** [comment] 2022-08-23 23:04
@ekansa and @robgaston 
At the moment, this behaviour is by design.

This happens because the graph name is used as the name of the root node of the graph as well.  The issue is that the name of the graph can be localized, but nodes (including the root node) cannot.  Therefore, the root node name will take the last localized name of the graph.  If you want to keep all the nodes in the same language then you'll want to set the graph name (and hence the root node name) to the language that you want all nodes to be in last.

**Comment by apeters** [comment] 2022-08-23 23:08
I'm closing for now as this is by design

**Closed by apeters** 2022-08-23 23:08 UTC
Labels: Type: Bug
