### ISSUE TITLE
v4.3.1 Default card component does not render multiple cards at the same tree level properly

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4170] opened 2018-10-05 23:51 UTC
When designing a branch that looks like:

-- Model
    -- Branch Top Node
        -- Data Collecting Node (e.g.: string)
        -- Data Collecting Node
        -- Data Collecting Node (e.g. Date, with place in a separate card selected)
            -- Data Collecting Node (e.g. string, child to Date node)

Arches' default card component only renders first two nodes in Editor (e.g.: link to Date/String card) is not shown until user creates a tile.  See: http://recordit.co/OmTqS2aKe0

**Comment by robgaston** [comment] 2018-10-08 18:44
@dwuthrich this behavior is by design; ie you cannot create the child tile until the parent tile is added, which is why you don't see them in the editor.  the default card component only edits one tile at a time.

**Comment by dwuthrich** [comment] 2018-10-08 19:38
@robgaston In my example all the data collecting nodes are at the same level (e.g.: three data collecting nodes all first level children) in the graph.  Instead, one node (and its child) simply has its "place nodes in a separate card" switched on.   I would expect the card component to render the widgets for two nodes and a link to the separate card by default.

**Comment by robgaston** [comment] 2018-10-18 15:42
I think we decided that this was not an issue & that perhaps all we need here is some better sign-posting (separate ticket).  Closing accordingly

**Closed by robgaston** 2018-10-18 15:42 UTC
