### ISSUE TITLE
Search Results Page: Results listed in the left panel should have markers on the map

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1712] opened 2017-02-28 19:26 UTC
### User Story

Search results are paged, with a listing of results in the left most panel of the search page.  For instances that have geometries on the page, a marker or icon should appear on the map.  If the user's cursor hovers over an instance in the left panel, the map marker associated with the instance should highlight (e.g.: change color).  

The marker and the highlight color should be configurable by an Arches system admin

**Comment by robgaston** [comment] 2017-02-28 19:54
this is a duplicate of #1697

**Closed** 2017-02-28 19:55 UTC
Labels: enhancement
