### ISSUE TITLE
File-list widgets do not enforce upload limit

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6763] opened 2020-10-20 23:48 UTC
**Describe the bug**

File-list widgets do not enforce their upload limits and allow users to add more files than specified.

**To Reproduce**
1. Load a package, afs was used here
2. Create a Resource Model with a node of file-list type, set the maximum number of files
3. Navigate to the Resource Editor, notice how  more than the maximum number of files can be uploaded
4. Notice the card can be saved.

**Screenshots**

**Expected behavior**
The maximum number of upload slots should be respected

**Comment by chiatt** [comment] 2024-03-14 23:07
Duplicate of #10135

**Closed by chiatt** 2024-03-14 23:07 UTC
Labels: Type: Bug, Priority: Low, Subject: Resource Manager
