### ISSUE TITLE
RDM: "duplicate key" exception after collection rename

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#2248] opened 2017-07-18 14:28 UTC
### Bug Report

After renaming a collection and then creating a new collection with the old name, I get a `duplicate key` exception. 

#### Expected Behavior
After renaming a collection, I expected the old name to become available again for use. 

#### Current Behavior
In this case I had a collection called `Date Type`, which I renamed and then created another collection called `Date Type`. This is the exception:
```
IntegrityError: duplicate key value violates unique constraint "concepts_legacyoid_key"
DETAIL:  Key (legacyoid)=(Date Type) already exists.
```

#### Steps to Reproduce (for bugs)

1. Create a collection called 'Date Type'
2. Rename that collection to something arbitrary
3. Create a new collection  called 'Date Type'
4. Nothing happens in the RMD
5. The Django log file shows the above exception

#### Your Arches Information

* Version used: master branch SHA 2fa77949618112bb90407f5fcd0be470c2e596a0 
* Browser Name and version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker)

**Comment by apeters** [comment] 2017-11-07 05:48
duplicate of #2198

**Closed by apeters** 2017-11-07 05:48 UTC
Labels: duplicate, RDM
