### ISSUE TITLE
styling breaks when Debug=True, using apache server

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#7514] opened 2021-06-15 17:57 UTC
**Describe the bug**

**To Reproduce**

**Screenshots**

**Expected behavior**

**Your Arches Information**

*   Version used:
*   Operating System and version (desktop or mobile):
*   Browser Name and version:
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by mradamcox** [comment] 2021-07-02 22:51
@whatisgalen Did you run collectstatic and do you have the apache Alias set up as described here? https://arches.readthedocs.io/en/latest/serving-arches-with-apache/
Also, if you are on Arches 5.2 using `django-compressor`, I just found that the apache user needs access to your static directory so that it can create/modify the CACHE directory that compressor creates in there.

**Comment by chiatt** [comment] 2022-04-01 18:26
@whatisgalen I think this must be a local issue or it has been resolved in another PR because I haven't been able to reproduce this on our QA instance. I suppose this could be specific to a particular arches release - in that case please reopen.

**Closed by chiatt** 2022-04-01 18:26 UTC
Labels: Type: Bug
