### ISSUE TITLE
Restrict basemaps or overlays based upon user groups

### ISSUE THREAD

**Issue by chrisdolby-HE** [archesproject/arches#5875] opened 2020-01-29 18:00 UTC
**Is your feature request related to a problem? Please describe.**
Within Historic England, we have a number of basemaps and data overlays that are copyright restricted, and currently we are unable to restrict access to basemaps or overlays to users who would be permitted to use them. We imagine others also have similar restrictions placed on them. We would like to make our versions of Arches publicly accessible, so we require an ability to place restrictions where we would also like to make use of these basemaps and overlays who use the Arches interface. They may or may not have the ability to create and edit within Arches.

**Describe the solution you'd like**
Restriction of basemaps or overlays to one or more defined user groups. It should be also possible to either not restrict basemaps or overlays to user groups or permit/select all user groups as being eligible to use them.

Basemaps or overlays that are unavailable should not be visible to user groups that are not permitted to use them. Basemaps or overlays that a user is permitted to work with appear within the list of basemaps or overlays as with any others that are unrestricted.

**Describe alternatives you've considered**
Providing a basemap through services/servers on a URL that is restricted to those user groups has been considered, but the user experience would be awful for those who aren't permitted - error messages or login prompts.

**Additional context**

**Comment by chiatt** [comment] 2022-05-27 00:14
Duplicate of #8162. Normally I'd close the more recent ticket, but there is already a PR created against #8162

**Closed by chiatt** 2022-05-27 00:14 UTC
Labels: Subject: Permissions Manager
