### ISSUE TITLE
Recent Edits Table only lists most recent imported assets.

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2715] opened 2017-11-08 23:00 UTC
### User Story

As a data editor, i expect the Recent Edits table to show the most recently edited resource instances, not just the bulk loaded instances.  This would allow me to quickly review and select instances that have been worked on by all editors.

#### Acceptance Criteria
- [ ] Table should show the most recent edited resource instances
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by mradamcox** [comment] 2017-12-07 17:35
Big +1 to this. The page is called "Recent Edits" but it does not show recent edits. It shows recently created resources. For a database whose main function is to collect condition assessment information about existing resources (not create new resources) this is not useful at all.

**Comment by mradamcox** [comment] 2017-12-07 17:53
It would also be great to have the user name listed for whoever made the edit. This is information was exposed in v3 of Arches.

**Comment by apeters** [comment] 2018-01-25 00:38
duplicate of #2293 , closing

**Closed by apeters** 2018-01-25 00:38 UTC
