### ISSUE TITLE
Copy a potion of a resource model as a branch

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1248] opened 2016-11-22 19:12 UTC
It would be desirable to be able to identify some non-top node in a resource model and copy it and all of its downstream nodes and edges as a branch.  That would make it possible to preserve and re-use edits made to graphs within resource models as branches that can be applied to other resource models.

**Comment by adamlodge** [comment] 2016-12-08 00:28
@apeters - could you give me some thoughts on how much effort this would take to implement?  This capability sure would be handy as we evolve the HIP graphs.

**Comment by dwuthrich** [comment] 2016-12-08 00:36
We should probably put this off until after we finish the current sprint and next sprint.  I think its a lower priority than search and import/export.

**Comment by jmunowitch** [comment] 2018-07-02 17:50
Duplicate of #3398

**Closed by jmunowitch** 2018-07-02 17:50 UTC
Labels: Subject: Card Designer, Subject: Card Manager, Subject: Graph Manager, Type: Enhancement
