### ISSUE TITLE
Add a graph setting to define a graph_id alias

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3316] opened 2018-05-02 18:55 UTC
This alias should be url friendlyfied 

this: `"my_friendly_name"` 

instead of this: `"a not very friendly name/alias"`

**Comment by azaroth42** [comment] 2019-01-23 20:51
Should be assigned to @robgaston ?

**Comment by robgaston** [comment] 2019-01-28 21:58
@apeters this is done in the `benosteen-4186_jsonld_export` branch (only can be managed from admin interface)

**Comment by apeters** [comment] 2019-01-31 22:03
this is fixed in the branch, but until it's merged into master I'll just leave this open

**Comment by azaroth42** [comment] 2019-02-04 17:55
I think a UI to set it should be added in the graph manager before the issue is closed. That doesn't need to be done today, but the functionality will go unused and eventually wither if there's no way to set it as a mere mortal.

**Comment by azaroth42** [comment] 2019-07-30 16:56
Ping, please.  In reconstructing all of the linked art models, they get new UUIDs and now all of the URIs are broken. This would be solved with just a couple hours work to put the entry box into the model's form.

**Comment by chiatt** [comment] 2020-07-07 20:39
Closing because resource model slugs are now available in arches

**Closed by chiatt** 2020-07-07 20:39 UTC
Labels: Audience: Administrator, Roadmap: Graph Designer Update - Task 1 (API), Subject: Graph Manager
