### ISSUE TITLE
Branches can not be edited when business data is present on the branch

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches#4302] opened 2018-11-19 17:44 UTC
**Describe the bug**
When there is business data present on nodes of a certain branch, then the entire branch cannot be expanded with new nodes.

This is problematic, as a database is often a work in progress and new requirements arise while data is being entered. 

**Screenshots**
No nodes can be added here, because resource instances of this model have data in one of the nodes within that branch
![image](https://user-images.githubusercontent.com/7893339/48724919-e041f280-ec2a-11e8-944b-54418d41da94.png)

**Expected behavior**
Graphs should be editable while data already exists, at least adding new nodes should not be problematic. 

**Your Arches Information**

*   Version used: 4.3.3
*   Operating System and version (desktop or mobile): Ubuntu 16.04 (Docker)
*   Browser Name and version: Chrome
*   Link to your Arches Install (optional): https://demo.globaldigitalheritage.org

**Comment by chiatt** [comment] 2018-11-20 12:38
I think the issue here is that you can't add nodes to a nodegroup if the nodegroup already has data, so the restriction is placed on the nodegroup rather than the entire branch.  The distinction being that  some nodegroups within a branch that do not have business data can still have nodes added. The reason for the restriction is that if you add a node to a card/nodegroup with business data, all of your future tiles would have a different shape than your existing tiles, so the restriction prevents the creation of tiles with missing nodes.  I'm not sure if it's clear how cards throughout the UI would respond to having tiles with different shapes.  If we were to lift this restriction, I think we would have to programmatically update all the existing tiles and their provisional edits if a new node was added to a nodegroup with data.

There is a setting: `OVERRIDE_RESOURCE_MODEL_LOCK = False` which was intended to development purposes. It was implemented in 4.1 but it doesn't seem to be working in 4.3.  I think a first step would be to fix this issue to allow admins to lift the lock. Once lifted, they could add a data migration to their project to update their tiles with the new node.

In the longer run it would be nice to allow admins to have full flexibility to modify their graphs and keep their existing business data in sync.

**Comment by veuncent** [comment] 2018-11-20 12:54
I see how the current implementation of Arches makes it difficult from a technical point of view to change node groups that contain business data, but I fear this will be quite hard to explain to our users. I foresee many small requests for a new field here and there, once our users start to get a grip on the platform and get ideas about what/how data really should be stored. 

For the time being, could you please provide more details about the data migration you mentioned? Would this involve a simple sql script? And if so, an example would be really helpful, because for me Arches' data structure is still quite hard to grasp. :)

Thanks!!

**Comment by chiatt** [comment] 2018-11-26 18:11
If you've added a node to a card with data, then you would need to add that node to each tile like so (using the nodegroupdid of the card you modified):
```
update tiles set tiledata = tiledata || jsonb '{"somenewnodeid":"somedefaultvalue"}' where nodegroupid = 'eb6ccd23-e742-11e6-84a6-026d961c88e6';
```
To remove a node from a tile, you can do so like this:
```
update tiles set tiledata = tiledata - 'somenewnodeid' where nodegroupid = 'eb6ccd23-e742-11e6-84a6-026d961c88e6';
```
Be sure that the default value supports the datatype for your node. To be certain you may try (after adding the new node) creating a resource instance and saving a new tile. Then find that tile in the tiles table, and use its `tiledata` value as an example that you can use to update all of your existing tiles.

**Comment by veuncent** [comment] 2018-11-26 20:12
Thanks Cyrus!

One question though: how do we add new nodes if the Graph Designer
prohibits it?

Oh and yet another question (logically follows from the previous one): can
we make up new guid for 'somenewnodeid' or do we get this from somewhere (I
suppose it depends on how that new node was created, as per question 1 :) )

**Comment by chiatt** [comment] 2018-11-27 23:29
@veuncent The answer to your second question is that you have to use the the nodeid created by the system when you added your new node (and the corresponding nodegroupid). The easiest way to do that is probably to look at the request in the network tab of your browser when saving a change to the node. 

Regarding your first question - The OVERRIDE_RESOURCE_MODEL_LOCK needs to be reenabled. That setting was intended to allow developers to add/remove nodes to nodegroups that already have associated data. Unfortunately this was not implemented in the new graph designer. 

Reenabling it should be fairly simple - a conditional just needs to be added here:
https://github.com/archesproject/arches/blob/05d828a935ad57bc95a75693bc84073eca4501d6/arches/app/views/graph.py#L174

If the OVERRIDE_RESOURCE_MODEL_LOCK is set to True, restricted_nodegroups should be an empty array.  There is also a validation error that will prevent you from adding a node. We would have to also prevent that error for getting thrown, but I don't that would be difficult.

**Comment by veuncent** [comment] 2019-01-27 19:17
Thanks @chiatt !

With your code I am able to edit node groups with existing instances, e.g. add additional nodes.  

However, when I try to edit the new node in an existing node group, the changes don't get picked up and the `Save edits` button does not appear.

In my case the node groups I am editing contain uploaded files, some over a GB, so I hope to find a solution that does not include deleting existing nodegroups :)

**Comment by chiatt** [comment] 2023-03-17 22:27
Closing as this will be addressed in 7.x with graph migrations

**Closed by chiatt** 2023-03-17 22:27 UTC
Labels: Type: Enhancement
