### ISSUE TITLE
Search: RDM concepts do not reference topmost concept label 

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1852] opened 2017-03-17 21:19 UTC
### Bug Report

typing a string into the search box shows strings that match the user's input.  Concepts are returned as:

Concept Label (concept scheme label)

However Arches returns the wrong concept scheme label.

For example:  BATTLEFIELD has the following heirarchy:

Lincoln_monument_types
... COMMEMORATIVE
...... BATTLEFIELD

Arches' search dropdown shows:

BATTLEFIELD (COMMEMORATIVE)  instead of BATTLEFIELD (Lincoln_monument_types)

**Comment by apeters** [comment] 2017-05-17 18:19
this is by design.  Right now the parenthetical is the Top Concept within a scheme.

**Comment by apeters** [comment] 2017-09-07 01:32
@dwuthrich , the issue with what you're proposing is that then everything under the Arches scheme with have `Arches` as it's parenthetical.  

What currently shows up as 
`Group (Actor Type)`
would now be
`Group (Arches)`

A solution to the issue you describe above would be to add a Scheme on top of the current Lincoln schemes, like this:

Lincoln
...Lincoln_monument_types
...... COMMEMORATIVE
......... BATTLEFIELD

Then in the Arches' search dropdown it would show:
`BATTLEFIELD (Lincoln_monument_types)` 
instead of
`BATTLEFIELD (COMMEMORATIVE)`

Either way the user has to setup their schemes and top concepts correctly.
Ideally we could have access to the full path because I've also noticed in some instances where there are many entries with the same parenthetical.  Like:

`Neighborhood (Evaluation Criteria Type)`

Arches
... Evaluation Criteria Type
...... Architecture and Engineering, 1850-1980
......... Housing the Masses, 1880-1975
............ Ranch House Neighborhoods, 1938-1975
............... Post-War Suburb
.................. Neighborhood

OR 

Arches
... Evaluation Criteria Type
...... Residential Development and Suburbanization, 1850-1980
......... Streetcar Suburbanization, 1888-1933
............ Suburban Planning and Development, 1888-1933
............... Streetcar Suburb
.................. Neighborhood

In these cases it might be nice to also display the direct parent, like this:
`Neighborhood (Evaluation Criteria Type...Streetcar Suburb)`
OR
`Neighborhood (Evaluation Criteria Type...Post-War Suburb)`

In the end, I'm not sure of the best solution.  The above solution would probably add some latency in retrieving the search results.

**Comment by dwuthrich** [comment] 2017-09-13 17:45
Alexei,

We didn’t get a chance to discuss this question, but I like the first solution.  No matter what, user’s will have to think through their concept hierarchy, and the first approach seems like the simplest and most performant.

-drw

Dennis Wuthrich
CEO Farallon Geographics  |  www.fargeo.com
601 Montgomery St, Suite 1095 | San Francisco, CA  94111
T 415 227 1140  |  Cell 415 317 2771

**Comment by apeters** [comment] 2017-09-13 18:54
@dwuthrich, if that's the case, then I think we can just close this ticket.  We can always reopen if we decide on a different course of action.

**Closed by apeters** 2017-09-13 18:54 UTC
Labels: bug, RDM, Task5
