### ISSUE TITLE
Arches does not show Provisional User edits made from mobile app

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4526] opened 2019-02-06 20:08 UTC
To reproduce:

1. Create a new instance from the mobile app when logged onto a MSM survey with a provisional user account
2. Synch the instance to Arches
3. Logon to Arches with the same provisional account and press the "my recent edits" button (located in upper right between the search and help buttons).
4. Note that the instance you created with the mobile app does not appear in the list of your edit history.

What should happen:
Arches should treat mobile edits and web-based edits for provisional users in the same way

**Comment by chiatt** [comment] 2019-06-20 15:02
I think this should be resolved in the latest

**Comment by chiatt** [comment] 2019-07-08 17:15
Hey @ajwuthrich, when you get a chance could you verify that this is now fixed?

**Comment by ajwuthrich** [comment] 2019-07-10 22:29
Works as intended.

**Closed by ajwuthrich** 2019-07-10 22:29 UTC
