### ISSUE TITLE
DB implementation to support node group level permissions

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#398] opened 2016-04-11 19:24 UTC
- [ ] Utilize the existing Auth module to support node group level permissions
- [ ] Add/remove node group level permissions on node group create/delete
- [ ] Allow multiple users/groups to be associated with node group level permissions in a single call
- [ ] Add unit tests

acceptance criteria:
- [ ] permissions successfully persisted to the database
- [ ] a documented model for storing & retrieving user and role based permissions for a given node group

**Comment by apeters** [comment] 2016-08-30 21:24
duplicate of #624

**Closed by apeters** 2016-08-30 21:24 UTC
Labels: Card Designer, duplicate
