### ISSUE TITLE
Time Wheel - Date Picker

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10294] opened 2023-11-24 01:36 UTC
Hi Team,

Reporting another bug for the Time Wheel function on 7.4.2 version of Arches. The date picker, when changing to the Yearly scroll, the months somehow disappear
 
![image](https://github.com/archesproject/arches/assets/150346658/c43f2590-f7b7-48fb-975e-affd4c8aedd1)

So users cannot choose a specific date when using the Date picker

**Comment by chiatt** [comment] 2023-11-29 23:38
Duplicate of #9060

**Closed by chiatt** 2023-11-29 23:38 UTC
Labels: bug
