### ISSUE TITLE
Mappop throws error

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6374] opened 2020-07-07 18:33 UTC
When clicking on a search marker, Arches shows the popup but throws the following error:

knockout-latest.js?_dc=5.0:79 Uncaught TypeError: Unable to process binding "if: function(){return !loading() }"
Message: Unable to process binding "if: function(){return permissions.users_without_edit_perm().indexOf(userid()) === -1 }"
Message: permissions.users_without_edit_perm is not a function
    at if (eval at parseBindingsString (knockout-latest.js?_dc=5.0:74), <anonymous>:3:74)
    at e (knockout-latest.js?_dc=5.0:75)
    at knockout-latest.js?_dc=5.0:77
    at a.o.l (knockout-latest.js?_dc=5.0:103)
    at Function.xd (knockout-latest.js?_dc=5.0:55)
    at Function.yd (knockout-latest.js?_dc=5.0:55)
    at Function.ha (knockout-latest.js?_dc=5.0:54)
    at Object.a.o.a.$ (knockout-latest.js?_dc=5.0:52)
    at init (knockout-latest.js?_dc=5.0:103)
    at knockout-latest.js?_dc=5.0:79

**Comment by chiatt** [comment] 2020-09-01 18:27
Duplicate of #6404

**Closed by chiatt** 2020-09-01 18:27 UTC
