### ISSUE TITLE
Some values from provisional edits  are initially missing when reviewing

### ISSUE THREAD

**Issue by pdpotter** [archesproject/arches#10612] opened 2024-02-15 14:48 UTC
Values selected using the `concept-select-widget` and `concept-multiselect-widget` by a user from `resource editor` group (not in the `resource reviewer` group) are initially missing when reviewing the edits. After clicking another card and then clicking back on the card with the `concept-select-widget` or `concept-multiselect-widget`, the value(s) are loaded.

**Comment by chiatt** [comment] 2024-04-02 23:27
Closing as a duplicate of #10633

**Closed by chiatt** 2024-04-02 23:27 UTC
Labels: Provisional Editing
