### ISSUE TITLE
Semantic Export

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#338] opened 2016-03-08 19:12 UTC
We need a json object (can be seperate from vanilla business data/tile export) that includes semantically rich export of instance data.  Can be a new object within aches json.

**Comment by apeters** [comment] 2017-08-22 20:45
this is a potential duplicate of #2307

**Comment by apeters** [comment] 2017-10-17 19:14
fixed by #2307

**Closed by apeters** 2017-10-17 19:14 UTC
Labels: Export, Import/Export
