### ISSUE TITLE
"arches-project create" command throws an error if a project of the same name already exists

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#10166] opened 2023-10-19 22:25 UTC
The error thrown is this
```
AttributeError: 'ArchesCommand' object has no attribute 'a_or_an'
```

It should instead show a message explaining the issue.

**Comment by jacobtylerwalls** [comment] 2023-10-19 22:48
Hey @apeters I think this is #10018

**Comment by jacobtylerwalls** [comment] 2023-10-19 22:49
Or at least somewhat similar :-)

**Comment by apeters** [comment] 2023-10-20 17:08
@jacobtylerwalls It's definitely similar, but different.  #10018 deals with invalid names, this ticket deals with duplicate names and throws a slightly different error and will require a different fix.

**Comment by jacobtylerwalls** [comment] 2024-04-12 19:51
Duplicate of #10759

**Closed by jacobtylerwalls** 2024-04-12 19:51 UTC
Labels: Type: Bug

**Comment by apeters** [comment] 2024-04-13 01:29
> Duplicate of #10759

I swear I searched for "a_or_an" and found nothing before I wrote #10759 🙏
