### ISSUE TITLE
add multiselect to dropdown select in MSM

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#4525] opened 2019-02-06 18:33 UTC
In a few input fields in MSM it lets you select from a dropdown list but closes when you click on a value. Need to add multiselect/keep the dropdown open so user doesn't have to keep clicking the input for each value they want to add.

**Comment by robgaston** [comment] 2019-02-06 19:01
I think that this is a duplicate of #4522 - I'm going to close this in favor of the (just slightly) earlier ticket

**Closed by robgaston** 2019-02-06 19:01 UTC
