### ISSUE TITLE
Bulk Loading does not execute pre_tile_save logic

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7837] opened 2021-09-22 13:05 UTC
**Describe the bug**

When using the `--bulk_load` flag during loading, any logic in the Datatype.pre_tile_save() does not get called and this is where the logic for creating resource to resource relationships exist.

There is also logic for File and Number datatypes that will get missed.

**To Reproduce**
Use the `--bulk_load` flag when loading data that contains resource-instance node data.

**Expected behavior**
Resource relationships that are created by resource-instance node data should be respected and become available after the load completes.

**Your Arches Information**

*   Version used: 5.2.x

**Ticket Background**
*   Found by: @aj_he

**Comment by chiatt** [comment] 2021-09-23 22:27
I think this is a duplicate of @6442

**Comment by chiatt** [comment] 2021-09-23 22:29
@aj-he I'm going to close this because it looks like a duplicate, but please reopen if I'm mistaken.

**Closed by chiatt** 2021-09-23 22:29 UTC
