### ISSUE TITLE
Graph Manager: Unable to edit graphs

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3459] opened 2018-05-31 23:41 UTC
#### Expected Behavior
When accessing the graph of an existing or new resource model, the user should be able to add new child nodes and branches to the graph, as well as be able to edit branches and nodes that already exist in the graph.

#### Current Behavior
When accessing a resource model's graph, whether the model is existing or new, the user is unable to edit the graph in any way. Any edits to existing branches fail, and clicking on the add buttons for new nodes or branches do not register.

#### Steps to Reproduce (for bugs)

http://g.recordit.co/L5A90Id9ab.gif
http://recordit.co/8fjRrVmvgu/gif/notify

1. Download Arches 4.2.0
2. Navigate to the Arches Designer
3. Select a Resource Model's graph or create a new Resource Model
4. Observe errors listed above.

#### Your Arches Information

* Version used: 4.2.0
* Browser Name and version: All browsers
* Operating System and version (desktop or mobile): Mac

**Comment by ajwuthrich** [comment] 2018-06-01 17:17
@chiatt also can't add or edit cards in the Card config. manager

**Comment by chiatt** [comment] 2018-06-03 18:31
This was due to a data type conflict in the resource index between the provisional flag when a user upgraded from 4.1.1.  I fixed the datatype issue and modified the steps of the upgrade.  @ajwuthrich QA'd and confirmed the fix worked for him so I'm closing this ticket.

**Closed by chiatt** 2018-06-03 18:31 UTC
Labels: Subject: Card Designer, Subject: Graph Manager, Type: Bug
