### ISSUE TITLE
Search Results Dowload should only create files for instances that appear in search results

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5712] opened 2019-12-17 00:40 UTC
It seems that search results export makes an export file for every model, even if no instances of the model appear in search results.  We should only create a model file if instances of the model appear in the search query

**Comment by apeters** [comment] 2019-12-20 19:02
I can't reproduce this error and neither can @chiatt , closing for now

**Closed by apeters** 2019-12-20 19:02 UTC
