### ISSUE TITLE
Core Datatypes not managed in ontology loader

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1522] opened 2017-01-27 21:44 UTC
The core datatypes for RDF are not managed by the ontology loader, including rdf:Literal (the class of all literal values), and more specific ones such as xsd:string, xsd:dateTime and so forth.
See in particular: https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes

In more recent versions of the CRM projected into RDF, these types are used, for example xsd:dateTime as the range of begin_of_the_begin and similar or rdf:Literal as the value of P3_has_note.  This results in networkx complaining that the node is not in the graph.

After adding them to the ontology manually, they're still not recognized properly ... unless I make rdf:Resource a subClassOf crm:E1_CRM_Entity... which is the wrong way around. I get an error trying to add an xsd:dateTime as a node in a branch to a Time-Span ... when it's the range of P82a (and similar), so should be valid.

I think the more granular issues are:
- [ ] process prefixes in ontology files (xsd:string --> full URI)
- [ ] Load RDF and RDFS ontologies before CRM
- [ ] Automatically add subClassOf rdfs:Resource if not stated
- [ ] Make rdfs:Resource the top most class, instead of E1_CRM_Entity
- [ ] Assert all of the xsd dataTypes as subClassOf rdfs:Literal

**Comment by azaroth42** [comment] 2017-01-28 01:45
Attached is an attempt to add rdfs:label as a valid property on any resource. It should have an xsd:string as its range, so I added a definition for xsd:string.  However in the branch designer, I do the following:

* Make a branch that is just xsd:string as a node, data type string so I can refer to it from other branches, as xsd:string doesn't appear in the class dropdown list.
* Make a "Name" branch, with top node of E41 Appellation.
* Add another Appellation as a child node
* Select that node, and try to add a node for xsd:string with the intent of using it as the label

I would expect to be able to add it, but I can't even though rdfs:label is valid for all classes.

Sometimes there is an error in the server log:
ValidationError: u'Can only append an undefined type graph to a child within a card collector type graph'

Other times not.

[cidoc_622.xml.zip](https://github.com/archesproject/arches/files/736616/cidoc_622.xml.zip)

**Comment by apeters** [comment] 2017-04-19 18:56
we had to add this to the current cidoc crm file used by Arches to handle this exact scenario:
```
<rdfs:Class rdf:about="E59_Primitive_Value">
    <rdfs:label xml:lang="en-US">Primitive Value</rdfs:label>
    <rdfs:comment>This class comprises values of primitive data types of programming languages or database management systems and data types composed of such values used as documentation elements, as well as their mathematical abstractions. 
</rdfs:comment>
</rdfs:Class>
<rdfs:Class rdf:about="E60_Number">
    <rdfs:label xml:lang="en-US">Number</rdfs:label>
    <rdfs:comment>This class comprises any encoding of computable (algebraic) values such as integers, real numbers, complex numbers, vectors, tensors etc., including intervals of these values to express limited precision
</rdfs:comment>
    <rdfs:subClassOf rdf:resource="E59_Primitive_Value"/>
</rdfs:Class>
<rdfs:Class rdf:about="E61_Time_Primitive">
    <rdfs:label xml:lang="en">Time Primitive</rdfs:label>
    <rdfs:comment>This class comprises instances of E59 Primitive Value for time that should be implemented with appropriate validation, precision and interval logic to express date ranges relevant to cultural documentation. 
</rdfs:comment>
    <rdfs:subClassOf rdf:resource="E59_Primitive_Value"/>
</rdfs:Class>
<rdfs:Class rdf:about="E62_String">
    <rdfs:label xml:lang="en">String</rdfs:label>
    <rdfs:comment>This class comprises the instances of E59 Primitive Values used for documentation such as free text strings, bitmaps, vector graphics, etc.
</rdfs:comment>
    <rdfs:subClassOf rdf:resource="E59_Primitive_Value"/>
</rdfs:Class>
```

**Comment by azaroth42** [comment] 2017-05-09 22:05
@apeters This is the issue I was describing today. See comment above for reference to the 622 ontology.   I tried adding:

```
<rdfs:Class rdf:about="rdfs:Resource">
	<rdfs:label xml:lang="en">Resource</rdfs:label>
</rdfs:Class>

<rdfs:Class rdf:about="rdfs:Literal">
	<rdfs:label xml:lang="en">Literal</rdfs:label>
	<rdfs:subClassOf rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
</rdfs:Class>

<rdf:Property rdf:about="rdfs:label">
	<rdfs:domain rdf:resource="http://www.w3.org/2000/01/rdf-schema#Resource"/>
	<rdfs:range rdf:resource="xsd:string"/>
</rdf:Property>
```
And things went horribly wrong 😀

**Comment by apeters** [comment] 2017-08-22 21:20
duplicate of #2306

**Closed by apeters** 2017-08-22 21:20 UTC
Labels: bug, RDM
