### ISSUE TITLE
Don't load an ontology by default when creating a project in Arches

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3713] opened 2018-07-18 20:52 UTC

**Comment by azaroth42** [comment] 2019-01-25 05:10
Duplicate of #3703?

**Comment by chiatt** [comment] 2019-06-06 19:19
This could also be a flag to not load ontologies

**Comment by chiatt** [comment] 2019-06-20 20:11
The default ontology is loaded in the first migration: https://github.com/archesproject/arches/blob/d3bee6050e74f4616317a95dfb9009cef2587d95/arches/app/models/migrations/0001_initial.py#L25
It looks like the task would be to remove it rather than prevent it from being loaded.

**Comment by chiatt** [comment] 2019-10-02 21:12
Meets requirements

**Closed by chiatt** 2019-10-02 21:12 UTC
