### ISSUE TITLE
Map Widget: Change Geocoder widget from dropdown to text box

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#955] opened 2016-10-14 22:20 UTC
### Bug Report

Map widget geocoder is implemented as a dropdown.  UX would be improved if the widget were implemented as a text box (would allow user to edit geocoded string more easily).  Geocoded results could be displayed using an AJAX panel.

See: http://recordit.co/yjc5wu4IHQ as an example (without showing json!)

Note that showing a fuller address match (eg: with city, state, postal code) should be the default and would allow users to better distinguish duplicate names.  For example, current geocoding widget displays multiple matches for "Mill Valley" without indicating one is in New York, another in California.

**Comment by chiatt** [comment] 2016-11-12 01:40
Duplicate of #908

**Closed by chiatt** 2016-11-12 01:40 UTC
Labels: enhancement, Widgets
