### ISSUE TITLE
save_system_settings returns TypeError

### ISSUE THREAD

**Issue by kokkytos** [archesproject/arches#6046] opened 2020-04-03 16:00 UTC
When I'm using 
`python manage.py packages -o save_system_settings `
 I get the following error:

> operation: save_system_settings
> Traceback (most recent call last):
>   File "manage.py", line 30, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/arches/management/commands/packages.py", line 281, in handle
>     self.save_system_settings(options["dest_dir"])
>   File "/home/leonidas/anaconda3/envs/arches2/lib/python3.8/site-packages/arches/management/commands/packages.py", line 1071, in save_system_settings
>     f.write(file["outputfile"].getvalue())
> TypeError: a bytes-like object is required, not 'str'

**Comment by chiatt** [comment] 2020-08-07 17:07
Confirmed that this is still a problem in stable/5.0.x, but it's resolved in master

**Comment by chiatt** [comment] 2021-12-28 22:40
Closing because the command works as expected in v6 and there will not be any more patch releases for v5.

**Closed by chiatt** 2021-12-28 22:40 UTC
Labels: Type: Bug
