### ISSUE TITLE
Mapbox API not working properly

### ISSUE THREAD

**Issue by himuura** [archesproject/arches#8987] opened 2022-09-16 15:02 UTC
**Describe the bug**
After inputing the Maxbox API key in the settings, jumping down to Search shows an empty screen.

**To Reproduce**
1. Input Mapbox API key on the Default Map Settings -> Mapbox API Key
2. Jump to the Search tab

**Screenshots**
![image](https://user-images.githubusercontent.com/24495945/190669882-960da03f-12dd-4b9c-a8fa-2a30476e218f.png)

**Expected behavior**
As in previous versions, a basemap should have appeared on the Search area.

**Your Arches Information**
*   Version used: 7.1.0
*   Operating System and version (desktop or mobile): Ubuntu 20.04
*   Browser: Chrome (latest)
*   Link to your Arches Install (optional): N/A

**Additional context**
N/A

**Ticket Background**
N/A

**Comment by robgaston** [comment] 2022-09-16 22:50
This bug is actually a duplicate of #8985 which has been addressed in the latest development branch. thanks for bringing this to our attention!

**Closed** 2022-09-16 22:50 UTC

**Comment by robgaston** [comment] 2022-09-16 22:52
@himuura a workaround for this in the 7.1.0 release is to delete that record in the system settings UI and apply these settings in settings.py.  you'll probably also have to restart your web server after that.

**Comment by himuura** [comment] 2022-09-19 09:08
> @himuura a workaround for this in the 7.1.0 release is to delete that record in the system settings UI and apply these settings in settings.py. you'll probably also have to restart your web server after that.

Could you perhaps shed some light on the record to delete from settings.py and what to apply?

**Comment by robgaston** [comment] 2022-09-19 21:01
@himuura yes, delete this:
![image](https://user-images.githubusercontent.com/1187406/191115701-b760cf3c-c21c-4569-a0a4-1550792f1d91.png)

then apply the settings in settings.py, as they are here (you'll probably just need to set the API key):
https://github.com/archesproject/arches/blob/3463eec2375d1f0985cb5743afdf2f553d15e5b5/arches/settings.py#L603-L607

then restart the web server.

**Comment by himuura** [comment] 2022-09-20 09:45
well, don't actually know if that's supposed but my settings.py was actually missing those entries...i had to manually copy and paste them. still no luck so far...

**Comment by robgaston** [comment] 2022-09-20 17:28
this bug is fixed in 7.1.1 which was released yesterday

@himuura there is an issue with these settings in 7.1.0 which can be worked around as per above.    I recommend upgrading to 7.1.1, at which point you will be able to assign these settings in the UI.

I note that  the error in your original screenshot does look to be unrelated to this.  failure to retrieve source maps shouldn't cause any functional issues, but it may point to some other issues at play with your system.

**Comment by himuura** [comment] 2022-09-20 17:33
> this bug is fixed in 7.1.1 which was released yesterday
> 
> @himuura there is an issue with these settings in 7.1.0 which can be worked around as per above. I recommend upgrading to 7.1.1, at which point you will be able to assign these settings in the UI.
> 
> I note that the error in your original screenshot does look to be unrelated to this. failure to retrieve source maps shouldn't cause any functional issues, but it may point to some other issues at play with your system.

Thank you mate!! Will try to update and install from scratch in the upcoming days to check if the issue still persists. Cheers!
