### ISSUE TITLE
Vertical Scroll in Graph Designer and Resource Editor Not Visible

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#7344] opened 2021-04-23 16:24 UTC
**Describe the bug**

When trying to access elements in the Graph Designer or Resource Manager which are off the bottom of the initial window view, it is not possible to scroll to them.  The vertical scroll bar is missing and the window view does not scroll down when the mousewheel or tabbing is used.

![image](https://user-images.githubusercontent.com/38533555/115899544-c4278880-a456-11eb-8785-3461063f2cec.png)
 
In the attached image, the missing scroll bar is highlighted.  This issue means it is not possible, in this example, to access the Node Data Type and Configuration section.

**To Reproduce**

1. Go to Graph Designer and open a Resource Model
2. Click on a Node within the Resource Model
3. Attempt to scroll down to view configuration settings off page
4. Error occurs - unable to scroll.

1. Go to the Resource Manager where the number of nodes do not fit on the page at once.
2. Attempt to scroll down to view all node inputs
3. Error occurs - unable to scroll.

**Expected behavior**

The user should be able to scroll to access all elements of the page.

**Your Arches Information**

*   Version used: stable/5.2.x branch
*   Operating System and version (desktop or mobile): Windows 10 Enterprise - Desktop
*   Browser Name and version: Chrome (89.0.4389.128) and Firefox (78.10.0esr (64-bit))

**Ticket Background**
*   Found by: @csmith-he

**Comment by csmith-he** [comment] 2021-04-23 16:24
@chrabyrd - here's the bug ticket I've raised

**Comment by chrabyrd** [comment] 2021-04-23 17:02
I unfortunately cannot reproduce this behavior in designer: https://recordit.co/Mq34jYt9Rb

However, I can reproduce this behavior in resource manager: https://recordit.co/fu9gKKqnJH

I'll cut a branch to fix the resource manager issue. If anyone is able to successfully reproduce the issue in graph designer, and would be willing to quickly touch base over Zoom, I may be able to track down what's happening.

**Comment by chrabyrd** [comment] 2021-04-26 17:04
This appears to be fixed in latest 5.2.x

**Closed by chrabyrd** 2021-04-26 17:04 UTC
Labels: Type: Bug
