### ISSUE TITLE
Allow domain values to be suplied in bulk to the domain widget

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2805] opened 2017-12-02 01:19 UTC
The Card Manager should allow a designer to upload the domain values from a csv file (file needs to include a single column of labels) or some other mechanism. 

- [ ] Card designer UI allows designer to populate the domain list from a simple csv file.

**Comment by ryan86** [comment] 2017-12-12 18:53
@dwuthrich Domain values can be saved and exported with resource models/branches meaning a user should only have to do manually entry of domain values once and they should be preserved with the model/branch on export/re-import. If a user is entering/managing a large amount of domain values should they use a collection instead?

**Comment by dwuthrich** [comment] 2017-12-12 20:24
This ticket is primarily for convenience.  Agree that in general we expect domains to be short lists, so your point about this being a one-time effort seems reasonable.  I don't have any issue putting this ticket in the Icebox for now

**Comment by chiatt** [comment] 2020-07-19 23:10
Duplicate of #2447

**Closed by chiatt** 2020-07-19 23:10 UTC
Labels: Roadmap: DISCO - Task 1 (Extend types widgets etc), Status: On Hold
