### ISSUE TITLE
clone of resource model does not copy menus and reports

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1746] opened 2017-03-02 16:47 UTC
When I make a clone of a resource that contains reports and/or menus, neither get copied into the new resource model that is created.  Expectation is that the new resource model would contain the cloned model's menus and reports.

**Comment by chiatt** [comment] 2017-03-14 13:06
Duplicate of #1658

**Closed by chiatt** 2017-03-14 13:06 UTC
Labels: bug, Import/Export
