### ISSUE TITLE
clickin on "i" button next to resource-instance value results in application hang

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6830] opened 2020-11-01 20:15 UTC
When clicking on this button after the resource-instance value is select, the application hangs.  
![Screen Shot 2020-11-01 at 12.12.01 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/ee277718-bce9-4f6a-9de1-4357585919d6)

![Screen Shot 2020-11-01 at 12.11.19 PM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/c5100f87-9fdc-40e8-962d-0d02a734f220)

**Comment by chiatt** [comment] 2020-11-02 22:57
Duplicate of #6762

**Closed by chiatt** 2020-11-02 22:57 UTC
Labels: Type: Bug
