### ISSUE TITLE
default language in RDM

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#2597] opened 2017-10-23 20:04 UTC
### User Story
As a an RDM data manager, I want to be able to configure the default language for concept labels. If time/budget disallows that, then I would very much prefer the default to be something other than Greek.  (For me, en-us would be a nice default language.)

**Comment by apeters** [comment] 2017-11-07 05:31
this is a duplicate of #1923

**Closed by apeters** 2017-11-07 05:31 UTC
Labels: duplicate, proposal, RDM
