### ISSUE TITLE
Resource model filter dropdown extends off page

### ISSUE THREAD

**Issue by mike-campbell-k-int** [archesproject/arches#3124] opened 2018-03-15 17:28 UTC
#### Definition of Done
Resource Models are displayed on screen correctly when Resource Model names are long.

### Bug Report
When clicking the button to select a Resource Model to search, if any of the resource model names are very long, all of the names will be off the screen to the left.

#### Expected Behavior
Users should be able to see all of the text of the Resource Model names.

#### Current Behavior
![image](https://user-images.githubusercontent.com/15122428/37480493-484e01f2-2877-11e8-9767-3ac886be44df.png)

**Comment by adamlodge** [comment] 2018-04-09 23:52
Still having issues.  See screenshot.

![screen shot 2018-04-09 at 4 47 12 pm](https://user-images.githubusercontent.com/9683819/38528859-572a3a26-3c16-11e8-9b4b-9e0288b5130b.png)

**Comment by chiatt** [comment] 2018-04-11 21:45
@ryan86 Being that I can't reproduce this and you're able to see it on your machine, would you mind looking into it?

**Comment by ryan86** [comment] 2018-04-11 22:30
@chiatt This now appears to be fixed on the dev and qa sites using Chrome and Firefox on Mac.

**Comment by ryan86** [comment] 2018-04-30 20:37
This still appears to happen when a user is not logged in.

![screen shot 2018-04-30 at 1 30 26 pm](https://user-images.githubusercontent.com/3038476/39448970-9c171e5e-4c7b-11e8-9924-7eb803c90529.png)

**Comment by ryan86** [comment] 2018-05-01 18:13
Not logged in:
![screen shot 2018-05-01 at 11 12 05 am](https://user-images.githubusercontent.com/3038476/39486339-9e024d46-4d30-11e8-93d1-ba40ede94782.png)

Logged in:
![screen shot 2018-05-01 at 11 12 22 am](https://user-images.githubusercontent.com/3038476/39486347-a4edbc12-4d30-11e8-8755-411f14141e79.png)


meets requirements

**Closed** 2018-05-01 18:13 UTC
Labels: Roadmap: DISCO - Task 8, Type: Bug
