### ISSUE TITLE
RDM has infinite nesting recursion

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#1582] opened 2017-02-05 23:27 UTC
Arches should probably not also be below Resource to Resource relationship types :)

![screen shot 2017-02-05 at 3 25 37 pm](https://cloud.githubusercontent.com/assets/871868/22630912/716d5b94-ebb7-11e6-8ae8-c29b40e34d75.png)

**Comment by apeters** [comment] 2017-02-06 17:44
duplicate of #1304

**Closed by apeters** 2017-02-06 17:44 UTC
