### ISSUE TITLE
There is an error when saving url datatype (probably when the value is none)

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#7816] opened 2021-09-09 23:24 UTC
There is an error when saving the tile which includes a url datatype.
It appears to be happening when the value is none.

```
2021-09-09 18:16:22,847 arches.app.views.tile ERROR    Saving tile failed [Tile id: ]                      [Exception message: AttributeError]                      [Exception trace: Traceback (most recent call last):
  File "/Users/njk/projects/arches_projects/arches_py3/arches/arches/app/views/tile.py", line 143, in post
    tile.save(request=request, transaction_id=transaction_id)
  File "/Users/njk/projects/arches_projects/arches_py3/arches/arches/app/models/tile.py", line 447, in save
    self.validate([])
  File "/Users/njk/projects/arches_projects/arches_py3/arches/arches/app/models/tile.py", line 346, in validate
    error = datatype.validate(value, node=node, strict=strict)
  File "/Users/njk/projects/arches_projects/arches_py3/arches/arches/app/datatypes/url.py", line 71, in validate
    if value.get("url") is not None:
AttributeError: 'NoneType' object has no attribute 'get'
]
Internal Server Error: /tile

```

**Comment by chiatt** [comment] 2021-12-15 21:47
Duplicate of #7992

**Closed by chiatt** 2021-12-15 21:47 UTC
Labels: Type: Bug
