### ISSUE TITLE
Maintain imported concept URIs

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#2386] opened 2017-09-02 16:14 UTC
### User Story

As a data manager for multiple projects, I want to ensure that imported concepts maintain their original identifiers, in order to provide cross-linking points between separate systems (Arches, or otherwise).

#### Acceptance Criteria
- [ ] Can determine the original URI of an imported concept in exports 
- [ ] ... and individual resource views
- [ ] Unit Tests passed
- [ ] Documentation

#### Expected Behavior

When importing a concept from AAT, I would expect the AAT identifier/URI to be maintained.

#### Current Behavior

URI is not recorded

#### Context

Interoperability and inter-system linking / alignment. I think this is a significant enough deficiency to call a bug (but feel free to reclassify as an enhancement)

**Comment by apeters** [comment] 2017-09-12 21:17
duplicate of #245

**Closed by apeters** 2017-09-12 21:17 UTC
Labels: bug, duplicate, RDM
