### ISSUE TITLE
The branches with same node alias cannot be added

### ISSUE THREAD

**Issue by njkim** [archesproject/arches#9035] opened 2022-10-14 23:19 UTC
**Arches Version/Branch:** 
6.2.x

**Describe the bug and how to reproduce it:**
In the graph designer, if a user attempts to add a branch to a resource that has the same node alias, adding fails. 

**Desired Behavior**
1. More details error message should be given if it has to fail
2. Reassign the alias when there is a conflict ? (currently adding suffix with sequential number).

**Comment by robgaston** [comment] 2022-10-15 16:03
@njkim this appears to be a duplicate of #8878

**Closed by robgaston** 2022-10-15 16:03 UTC
Labels: Type: Bug
