### ISSUE TITLE
Add a way to exclude coordinates from reports that use a map header

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6645] opened 2020-09-24 15:37 UTC
Actual coordinate data on reports seems redundant and messy when it already shows the  resource's geometry on a map.  If there really are uses cases that require the coordinates in the report, then there can be a switch to show them on either at the report design level or at the instance level.

**Comment by chiatt** [comment] 2020-10-09 17:53
Duplicate of #4774

**Closed by chiatt** 2020-10-09 17:53 UTC
