### ISSUE TITLE
"Choose a data type" can be selected for datatype causing error

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches#11034] opened 2024-06-12 15:07 UTC
dev/7.5.x - possibly in earlier versions too

When selecting a datatype in the graph builder, the option "Choose a data type" can be selected
![image](https://github.com/archesproject/arches/assets/119508494/3ba2b23b-a739-4bb2-9385-6d5348d58fbd)

This causes the following error in the backend when attempting to save edits, and an endless load in the front end.
```
Traceback (most recent call last):
  File "/home/samuel/arches_dev/arches_her/arches/arches/app/datatypes/datatypes.py", line 93, in get_instance
    d_datatype = DataTypeFactory._datatypes[datatype]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: ''
```

**Comment by jacobtylerwalls** [comment] 2024-06-12 15:19
Hey @SDScandrettKint good catch. Noticed it's a duplicate of #10362.

**Closed by jacobtylerwalls** 2024-06-12 15:19 UTC

**Comment by SDScandrettKint** [comment] 2024-06-12 15:26
> Hey @SDScandrettKint good catch. Noticed it's a duplicate of #10362.

Ah, thanks for noticing it was a duplicate @jacobtylerwalls - I tried to search for it in the existing issues but couldn't find it, my bad!
