### ISSUE TITLE
Arches Designer: Add "export" command to Manage... menu

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2730] opened 2017-11-09 21:42 UTC
### User Story

As an Arches designer, I often want to export a branch/model that I am working on.  Arches currently requires that I exit the graph manager/card manager and navigate to the branch that I want to export.

Desired behavior:  allow designer to export their branch/model while still working within the graph manager or card manager

**Comment by jmunowitch** [comment] 2018-08-31 19:17
Duplicate of #3738.

**Closed by jmunowitch** 2018-08-31 19:17 UTC
