### ISSUE TITLE
Should be able to view null fields by default, and set that config in report design

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6644] opened 2020-09-24 15:13 UTC
As part of resource models report configuration, an administrator should be able to set the default value for the "Hide Null Values" option in the resource instance reports.  

I would also argue that most implementations will prefer for it to be set to "show null values" (at the config level) rather than hide them.  This is because most datasets dont contain gazillions of records and hiding the fields that contain the null values can be misleading when doing QA on data loading operations.

Screenshot to clarify the existing instance-level config I'm talking about.
![Screen Shot 2020-09-24 at 8.05.30 AM.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/f0700d56-5a31-4946-9295-c4ee61ed943a)

**Comment by chiatt** [comment] 2020-09-24 16:59
Duplicate of #6622

**Closed by chiatt** 2020-09-24 16:59 UTC
