### ISSUE TITLE
Arches Designer: Add "clone" command to Manage... menu

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2729] opened 2017-11-09 21:40 UTC
### User Story

As a graph designer, i often want to clone a branch so that I can use it as the starting point for a new design.  At present, Arches requires me to return to the branch library, navigate to the branch I want, then clone the branch.

Desired behavior: allow designer to clone a brach while working within the graph manager or card manager.  Selecting the clone command should navigate the designer to the summary page of the cloned branch/model so that they can immediately rename/configure the newly cloned graph

#### Acceptance Criteria
- [ ]
- [ ]
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by jmunowitch** [comment] 2018-08-31 19:17
Duplicate of #3738.

**Closed by jmunowitch** 2018-08-31 19:17 UTC
