### ISSUE TITLE
Edited branches do not update automatically on resource models to which they are attached

### ISSUE THREAD

**Issue by azerbini** [archesproject/arches#1922] opened 2017-04-03 13:05 UTC
#### Expected Behavior

When editing a branch (in the graph designer) which is already attached to one or more resource models, one would expect those changes to automatically reproduce themselves in the resource models (since one cannot add new nodes to a branch once this has been appended to a resource model).

#### Current Behavior

Edits to branches do not currently appear in the resource models they are attached to. One has to delete the branch in the resource model and reappend it in order for the changes to show up.

#### Your Arches Information

* Version used:4.0b3
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): Yosemite

**Comment by dwuthrich** [comment] 2017-04-03 13:56
@azerbini This behavior is by design.  Attaching a branch to a model means that a user may then customize the branch for a particular model without changing the base branch.

As you note, if you want to ensure that a change to a branch is universally implemented, simply remove the card from the model, modify the branch, and then re-attach the branch to the model.  Your edited branch will then be the "base" version every model uses.

**Comment by azerbini** [comment] 2017-04-03 14:41
@dwuthrich Yep, that makes sense, but it doesn't seem to work.If I try to add a Node/Node Type combo (or, for that matter, a simple Node) to a branch attached to a resource model, I get the message 'Can't append a graph to a resource except at the root'. As far as I can see, in the current setup, a user cannot customise a branch for a particular model, once that branch is attached to said model.

**Comment by apeters** [comment] 2017-04-19 18:41
@dwuthrich do we want to allow users to edit branches that are attached to a resource, or is the workflow to remove the branch from the resource, edit the base branch, and then re-add the branch?

**Comment by apeters** [comment] 2018-01-24 19:48
I'm closing this, because the basic premise that branches on a resource reference branches in the branch library is false.

**Closed by apeters** 2018-01-24 19:48 UTC
Labels: Graph Manager
