### ISSUE TITLE
In Search, when the top bar of the TimeFilter datepicker is clicked it breaks UI

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#6744] opened 2020-10-20 00:00 UTC
**Describe the bug**

In Search, the 'From' and 'To' fields are datepicker components. When the top bar of the datepicker is clicked, the datepicker UI is broken so that the user cannot select a new date, and only refreshing the page fixes it.

**To Reproduce**
1. Navigate to Search, and find the TimeFilter
2. Notice the 'From' and 'To' fields, click them to interact with the datepicker component
3. Click the top bar of the datepicker component. Notice how it break UI.

**Screenshots**

https://ibb.co/72PCqcJ

**Expected behavior**

Selecting the top bar should allow the user to manually enter the month/year

**Comment by chiatt** [comment] 2023-02-18 01:13
Duplicate of #9060.

**Closed by chiatt** 2023-02-18 01:13 UTC
Labels: Type: Bug, Subject: Search, Audience: End User
