### ISSUE TITLE
Can only view Related Resources when logged in

### ISSUE THREAD

**Issue by adalgity** [archesproject/arches#2376] opened 2017-08-25 14:34 UTC
Not logged into Arches, clicked Related Resources (for Lincoln Cathedral, which has resources related). Get "No Resources Selected" error.

Logged in as "Admin," and repeated same thing--i.e., click Related Resources for Lincoln Cathedral. Then all is well--i.e., both grid and graph for related resources appear.

See 2 screenshots attached: 1) not logged in; 2) logged in.
![related_resources_not_logged_in](https://user-images.githubusercontent.com/29263468/29718474-c604b064-8967-11e7-9e21-cce39a7c9f54.png)
![related_resources_bug_logged_in](https://user-images.githubusercontent.com/29263468/29718479-c844ba68-8967-11e7-8d48-c2d291249ce6.png)

**Comment by mradamcox** [comment] 2017-08-26 19:21
Looks like this is caused by [this decorator](https://github.com/archesproject/arches/blob/master/arches/app/views/resource.py#L335) (which in stable/4.0.x was [slightly different](https://github.com/archesproject/arches/blob/stable/4.0.x/arches/app/views/resource.py#L336)). I'm removing this locally for the CIPA presentation, but what was the rational for that decorator in the first place?

**Comment by mradamcox** [comment] 2018-02-19 23:00
This seems to be fixed forever ago (thanks @chiatt), so I'm closing the issue. Guest users have full access to the related resource graph.

**Closed by mradamcox** 2018-02-19 23:00 UTC
