### ISSUE TITLE
reCaptcha error prevents user from creating a new account

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches#9050] opened 2022-10-24 21:15 UTC
@johnatawnclementawn commented on [Fri Oct 21 2022](https://github.com/archesproject/arches-for-science-prj/issues/1040)

Version: 6.2.x via Docker

Describe the bug and how to reproduce it:
When attempting to create a new account at http://localhost:8001/auth/signup, I am unable to create a new account because the captcha window displays an error: ERROR for site owner: Invalid site key.
There are no errors present in the browser console.

![Screen Shot](https://user-images.githubusercontent.com/22161487/197289959-d3cc1651-7e23-4029-ab8a-27f2a2e8ed18.png)

**Comment by SDScandrettKint** [comment] 2024-01-10 10:13
I have recently experienced this myself, however, it is not a bug per se.  For anyone experiencing this error, it arises when `ENABLE_CAPTCHA = True` in the core Arches or project settings.py and `RECAPTCHA_PUBLIC_KEY` and `RECAPTCHA_PRIVATE_KEY` are unset or commented out.

Setting `ENABLE_CAPTCHA` to False, or generating a reCAPTCHA and adding the public and private key into the settings, will solve this and allow for the creation of user accounts.

**Comment by chiatt** [comment] 2024-01-25 17:52
I'm going to close this because the ENABLE_CAPTCHA setting is described in the documentation

**Closed by chiatt** 2024-01-25 17:52 UTC
Labels: Type: Bug
