### ISSUE TITLE
Report Manager: error when dragging and dropping a new report

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1040] opened 2016-10-24 18:00 UTC
Dragging and dropping a report template to add it to a Resource Model results in this console error: Uncaught ReferenceError: Unable to process binding "text: function (){return template.name }"
Message: template is not defined

The report does seem to be added though, after refreshing the page (not shown in the video below).
### Steps to Reproduce

http://recordit.co/GjlpFQ3TXK

**Comment by apeters** [comment] 2016-11-02 06:26
I can't reproduce this error.  This seems to be fixed in the latest.

**Closed by apeters** 2016-11-02 06:26 UTC
