### ISSUE TITLE
Help Menu issue on the Image Card

### ISSUE THREAD

**Issue by JPdelaRosa83** [archesproject/arches#10433] opened 2023-12-14 04:00 UTC
Hi Team,
Another cosmetic issue we have found on 7.4.3 but also visible on previous versions I believe.

We are using the Card Type = File Viewer on our Image node to upload photos for our Resource Data. We have the Enable Card-level help which will enable the HELP menu
![image](https://github.com/archesproject/arches/assets/150346658/98a1208c-15e3-47ff-9621-8b170e7c2cf9)

However, when uploading the file, the HELP menu is not visible
![image](https://github.com/archesproject/arches/assets/150346658/e426dd5a-0770-4881-b113-7ae4b7d6d9db)

But instead, the HELP option it is visible when EDITING the file after the upload and looks obscured 
![image](https://github.com/archesproject/arches/assets/150346658/96a231c9-1960-4479-a102-d3c4ec53e892)
![image](https://github.com/archesproject/arches/assets/150346658/2585c352-b845-4112-bb7b-3229914f7ef2)

**Comment by jacobtylerwalls** [comment] 2023-12-14 13:27
Thanks for raising the issue!

I think this is a duplicate of #10318, so will be closing.

**Closed by jacobtylerwalls** 2023-12-14 13:27 UTC
