### ISSUE TITLE
Number widget does not respect placeholder text

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8758] opened 2022-08-04 18:27 UTC
**Describe the bug**

The number widget appears to not respect placeholder text, and instead auto-populates with a `0`. This behavior is also apparent in the Resource manager.

**To Reproduce**
1. Navigate to arches designer
2. select a resource model with a number widget
3. navigate to `card` tab for number widget
4. notice it does not respect placeholder text

**Screenshots**

<img width="1409" alt="Screen Shot 2022-08-04 at 11 26 00 AM" src="https://user-images.githubusercontent.com/9162695/182924229-1a1680ba-99a3-4cdc-83ce-41307249bed2.png">

**Comment by chiatt** [comment] 2022-08-17 22:17
Duplicate of #8487

**Closed by chiatt** 2022-08-17 22:17 UTC
Labels: Type: Bug
