### ISSUE TITLE
bug: cant access cards related to branches

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1676] opened 2017-02-22 21:44 UTC
When trying to access the card related to a branch, I get error message: 'NoneType' object has no attribute 'ontologyproperty'

This issue does not exist when accessing the cards related to a resource model.

**Comment by chiatt** [comment] 2017-02-23 00:40
@adamlodge 
@apeters solved the issue.  I am going to update the branch editing instance now.

**Comment by chiatt** [comment] 2017-02-23 22:35
Duplicate of #1661

**Closed by chiatt** 2017-02-23 22:35 UTC
Labels: bug
