### ISSUE TITLE
Summary report display for the resource instance type is broken

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#7359] opened 2021-04-28 05:55 UTC
**Describe the bug**
Clicking on the small "i" button on a related resource instance widget causes the page to hang

![Screen Shot 2021-04-27 at 10 44 16 PM](https://user-images.githubusercontent.com/823773/116352981-e00a9180-a7aa-11eb-90b9-4803d2d9fb9e.png)

It looks like this was caused by the work done in re #7262, specifically ["_load_resource_data"](https://github.com/archesproject/arches/blob/master/arches/app/views/resource.py#L702) can return either a context object or a JSONResponse object.  It's the return of the JSONResponse object that causes the issue.

**Comment by chrabyrd** [comment] 2021-04-28 17:11
looks to be a duplicate of #7322 , closing

**Closed by chrabyrd** 2021-04-28 17:11 UTC
Labels: Type: Bug
