### ISSUE TITLE
Search Page: replace current geospatial filter with one based on new map card

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5188] opened 2019-08-22 20:57 UTC
Update the current map filter in the default Arches search page with the map UI used in the new map card component.

Replace the "edit" tab with a "buffer" tab to support geospatial filters

**Comment by robgaston** [comment] 2019-09-04 23:45
duplicate of #4984

**Closed by robgaston** 2019-09-04 23:45 UTC
