### ISSUE TITLE
Create Resource Instance Card Component needs to support a way to cancel editing

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5074] opened 2019-08-05 21:14 UTC
When creating a new instance while working on a workflow, the create resource instance card component only allows a user to "save" (see image).  There should be a way (such as a "cancel" button) to dismiss the card without providing any data.

![Screen Shot 2019-08-05 at 2.10.57 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/02fbd2b8-972e-4e76-8c01-6102a43d5ca0)

**Comment by chiatt** [comment] 2019-08-23 16:02
Duplicate of #4915

**Closed by chiatt** 2019-08-23 16:02 UTC
