### ISSUE TITLE
Copy tiles enhancement

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#5772] opened 2019-12-23 22:53 UTC
A client has an issue where they are creating many tiles from a given card.  The values within each tiles are only slightly different.  They want a way to easily duplicate the values of existing tiles into new tiles and then just make the small delta in the values necessary for their work.

One potential solution that occurs to me is to create a way to copy tiles from the tree on the left of the screen, paste them on to the tree in a dirty state where values can be edited and the save button pressed.

**Comment by chiatt** [comment] 2020-05-04 16:58
Duplicate of #5984

**Closed by chiatt** 2020-05-04 16:58 UTC
Labels: Type: Enhancement
