### ISSUE TITLE
Templates Manager: Provide a UI to allow admins to configure search, map pop-up, related resources pop-up content

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1089] opened 2016-10-28 20:44 UTC
### User Story

Arches admins will need to define the nodes that will populate content for the templates that define search results, map pop-up, and related resources pop ups.

**Comment by apeters** [comment] 2016-11-02 17:20
isn't this the same as #847 ?

**Comment by robgaston** [comment] 2016-11-02 17:28
@apeters I believe you are correct

**Comment by apeters** [comment] 2016-11-15 20:34
closing as duplicate of #847

**Closed by apeters** 2016-11-15 20:34 UTC
Labels: enhancement
