### ISSUE TITLE
Define Resource Descriptors: Allow multiple nodes to be selected for Map Pop-up

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1729] opened 2017-03-01 01:39 UTC
### User Story

As a resource model designer, I may wish to show content from multiple nodes in the map pop-up when a user selects an instance on the search map.

The Define Resource Descriptors function should allow me to select and order multiple nodes (similar to how we allow a user to manage cardinality results in a card) to define the content of my map pop-up

**Comment by chiatt** [comment] 2020-08-03 22:49
Duplicate of #2720

**Closed by chiatt** 2020-08-03 22:49 UTC
Labels: Type: Enhancement
