### ISSUE TITLE
Workflows - spell checker freezes page

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8219] opened 2022-02-11 09:08 UTC
**Describe the issue** - When using the spell checker on text boxes e.g., Proposal Description, the pages freezes and you cannot cancel or exit the spell checker. Reloading the page fixes issue.

**Steps to reproduce**

1) Open a Consultation workflow

2) On the Application Proposal step, enter some text and open the spell checker:

![image](https://user-images.githubusercontent.com/78143228/153564348-1de57282-340f-4a56-8a3b-cdf81d0f7893.png)

**Comment by chiatt** [comment] 2022-04-11 23:24
Duplicate of #8210

**Closed by chiatt** 2022-04-11 23:24 UTC
Labels: Type: Bug
