### ISSUE TITLE
Graph Manager: Permission Manager Application UI

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#355] opened 2016-03-22 19:07 UTC
- [ ] Abstract List View spawns form to list users and groups
- [ ] Ability to associate a given node group-level permission to the selected user/group and call the appropriate end point
- [ ] Ability to apply permissions to multiple users/groups at a time

acceptance criteria:
- [ ] users should only be allowed to select grouping nodes
- [ ] go to graph manager for test graph:  {URL HERE!}, view permissions for a given node group
- [ ] change permissions for a given node group and save
- [ ] verify that changes are reflected in the UI, refresh page and check again
- [ ] document it

**Comment by apeters** [comment] 2017-02-15 20:04
duplicate of #1112, #1113, #1114, #1115

**Closed by apeters** 2017-02-15 20:04 UTC
Labels: duplicate, Graph Manager
